### ISSUE TITLE
Sidedness issue - Client crash when wearing boots on a server.

### ISSUE THREAD

**Issue by ProsperCraft** [DenisMasterHerobrine/TravellersBoots#2]
https://gist.github.com/Reveter/f3d27338997b04fff74b02301fd2addf#file-gistfile1-txt-L6

This doesn't happen in single player, only when on a dedicated server.

**Comment by DenisMasterHerobrine** [comment]
Thank you for the report! I'll try to fix that soon as I can.

**Comment by DenisMasterHerobrine** [comment]
Fixed in 1.1.1. This version will be released after some time on CurseForge. Thanks for your patience.
