### ISSUE TITLE
Craft recipe?

### ISSUE THREAD

**Issue by ParzivalWolfram** [DenisMasterHerobrine/TravellersBoots#3]
Craft recipes don't seem to be posted anywhere and they don't show up in the craft book. I'm using 1.14.4, not that it would matter.

**Comment by DenisMasterHerobrine** [comment]
Crafting recipes can be viewed through [JEI](https://www.curseforge.com/minecraft/mc-mods/jei) , if it isn't installed in modpack - you can find Mod Showcase on CurseForge page, the recipes for 1.12.2 and 1.14.x versions are the same.

**Comment by ParzivalWolfram** [comment]
Funnily enough, the recipes shown in the modpack didn't work UNTIL I
installed JEI.
