### ISSUE TITLE
stupid edge skip

### ISSUE THREAD

**Issue by MarcinKielbaszewski** [DenisMasterHerobrine/TravellersBoots#4]
That edge skip killed me enough times to post this issue

**Comment by DenisMasterHerobrine** [comment]
What do you mean by this? Which Traveller's Boots version you use?

**Comment by MarcinKielbaszewski** [comment]
W dniu 2019-11-27 14:13:18 użytkownik DenisMasterHerobrine <notifications@github.com> napisał:
What do you mean by this? Which Traveller's Boots version you use?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
i mean when you are on the edge of a block it wont detect the liquids such as lava and may cause many deaths when you hold shift and just fall in it (annoying thing is that the effect of skipping the edges will stay even if you take off the boots) I was using version 1.0.0

**Comment by DenisMasterHerobrine** [comment]
Please, try 1.0.4 verison of Traveller's Boots, let me know if this issue persists.
