### ISSUE TITLE
step height bug in latest 1.12.2 version

### ISSUE THREAD

**Issue by Aldaria-Games** [DenisMasterHerobrine/TravellersBoots#6]
After taking off a pair of Mk2 boots, the step height increase effect remains active. I do not know for sure how long it lasts, but it seems like it lasts until next death.

This may affect 3 and 4 as well, it's worth a check at least.

**Comment by DenisMasterHerobrine** [comment]
Hello, thanks for the report, my apologies for that bug in 1.12.2 since I fixed these things in only 1.14+ versions and forgot about 1.12.2 one. This bug is reproduced and will be fixed soon.
